echo Processing Further....
echo Please wait till Setup completes. It may take upto 5-10 according to your internet speed. Kindly wait...
pip install -r ".\res\install\requirements.txt"
if %errorlevel%==1 start cmd /c "echo Setup Unsuccessfull.requirements.txt file does not exists. && pause
if %errorlevel%==0 start cmd /c "echo Setup Completed Successfully. && pause
